name: mess
description: >
  **Mass Entity State System (MESS)** is a robust ECS (Entity-Component-System) library for Flutter
  designed to manage large-scale entities and their states.
  MESS enables developers to build complex systems with a clear architecture, ensuring high performance and scalability.

version: 0.0.1-pre.1

homepage: https://github.com/PlugFox/mess

repository: https://github.com/PlugFox/mess

issue_tracker: https://github.com/PlugFox/mess/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - ecs
  - entity-component-system
  - state-management
  - game-development
  - mass-entity-state-system

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the library.'
#    path: example.png

environment:
  sdk: ^3.5.0
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter
  # Annotations
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  fake_async: ^1.3.0
  flutter_lints: '>=4.0.0 <6.0.0'

flutter:
